Repository rooneyshuman/SFTP-App, pull requests merged in 2020-03, with the labels that each got.

#11 Disconnect() unit test/method modifications
  pom.xml
  src/main/java/edu/pdx/cs/sftp/Client.java
  src/test/java/edu/pdx/cs/sftp/ClientTest.java
Labels: enhancement

#12 Modify documentation for getters
  src/main/java/edu/pdx/cs/sftp/Client.java
Labels: documentation

#13 Modify methods for displaying local/remote files
  src/main/java/edu/pdx/cs/sftp/Client.java
  src/test/java/edu/pdx/cs/sftp/ClientTest.java
Labels: documentation, enhancement

#14 User class reformatting, restructuring, renaming, and debugging modifications
  src/main/java/edu/pdx/cs/sftp/User.java
  src/test/java/edu/pdx/cs/sftp/UserTest.java
Labels: documentation, enhancement

#17 Modify print methods
  src/main/java/edu/pdx/cs/sftp/Client.java
Labels: documentation, enhancement

#16 Modify create remote directory methods
  src/main/java/edu/pdx/cs/sftp/Client.java
Labels: enhancement

#18 Modify change local directory method
  src/main/java/edu/pdx/cs/sftp/Client.java
  src/test/java/edu/pdx/cs/sftp/ClientTest.java
Labels: documentation, enhancement
